### ISSUE TITLE
好像只能测试假期的第一天，第二天就会出现bug 比如2017年的1月2号 就显示是工作日

### ISSUE THREAD

**Issue by wulongcomputer** [bastengao/chinese-holidays-go#1]
好像只能测试假期的第一天，第二天就会出现bug 比如2017年的1月2号 就显示是工作日

**Comment by bastengao** [comment]
已修复 https://github.com/bastengao/chinese-holidays-go/commit/97c8a177ff163e5b84a40fd5b8cb53845298689d , 再试下。

**Comment by bastengao** [comment]
先关了，有问题再重开。
