### ISSUE TITLE
能否辛苦补充一下2022节假日呢

### ISSUE THREAD

**Issue by ysluckly** [bastengao/chinese-holidays-go#3]

**Comment by bastengao** [comment]
感谢提醒，已发布 v1.1.0

**Comment by ysluckly** [comment]
感谢您提供这么一个日期库，很实用




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bastengao/chinese-holidays-go"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月4日(星期四) 上午10:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bastengao/chinese-holidays-go] 能否辛苦补充一下2022节假日呢 (Issue #3)





 
感谢提醒，已发布 v1.1.0
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
